#!/bin/bash
#title          :enablewifi
#description    :Enables Wifi in Linux mint 19
#author         :mrblue
#date           :20191228
#version        :1.0
#usage          :./enablewifi
#bash_version   :4.4.20(1)-release
#============================================================================
git clone https://github.com/lwfinger/rtlwifi_new.git -b rtw88
cd rtlwifi_new
make
sudo make install
