#!/bin/bash
#title          :notify
#description    :Notifies the user with an audio
#author         :mrblue
#date           :20191228
#version        :1.0
#usage          :./notify
#bash_version   :4.4.20(1)-release
#============================================================================

paplay /usr/share/sounds/freedesktop/stereo/complete.oga
msg=$1
if [ -z "$msg" ]
then
    msg="Completed!"
fi
notify-send $msg
