#!/bin/bash     
#title          :scrasfile
#description    :Captures the screenshot of the window as a file
#author         :Gopalakrishnan
#date           :20191228
#version        :1.0    
#usage          :./scrasfile
#bash_version   :4.4.20(1)-release
#============================================================================        

#! /bin/bash
DEST_PATH=/run/media/krishna/Storage/Career/XPO/Screenshots
mkdir -p $DEST_PATH && import -window root $DEST_PATH/$(date +%Y%m%d%H%M%S).png
